### ISSUE TITLE
Channel Operator Tools

### ISSUE THREAD

**Issue by examknow** [examknow/MH-WikiBot#1]
**Feature Name**
ChanOP Tools
**What will it do?**
Allow channel operators to manage their channel using the bot
**Suggested Stalkwords**
!opme
!deopme
**Who can use it?**
Chanops group
**Does it need access to other APIs**
No
**Have you discussed it with the team?**
Discussed on IRC

**Comment by RhinosF1** [comment]
Will look into this tommorow
-- 
Thanks,
Samuel

**Comment by examknow** [comment]
I say we put this on hold for the next version so that we can get the beta-01 deployed.
@RhinosF1 thoughts?

**Comment by examknow** [comment]
Task is {{done}}. Per [92cf00be3829466db0429e7023c2882e5b532930](https://github.com/examknow/MH-WikiBot/commit/92cf00be3829466db0429e7023c2882e5b532930). I will open a pull request to merge the beta-01 branch.
