### ISSUE TITLE
Add Logging Support

### ISSUE THREAD

**Issue by examknow** [examknow/MH-WikiBot#2]
The bot will need to log each API request with the following items

-  The nick and hostmask of the user that sent the request
-  The action requested
-  The reason for the action

These logs will go to the private **#SigmaBot-logs** channel where they can be reviewed by administrators and provided to Miraheze staff on request.

**Comment by sario528** [comment]
If you want to keep the logs for any length of time, I recommend storing them somewhere else in addition to an IRC channel.

**Comment by examknow** [comment]
@sario528 We can also use SigmaBot to store channel logs.

**Comment by examknow** [comment]
{{done}} Per [211f8d5d16dc8d6d710e11c09cee732dd56b2ff6](https://github.com/examknow/MH-WikiBot/commit/211f8d5d16dc8d6d710e11c09cee732dd56b2ff6)
