### ISSUE TITLE
!log and !delete command not working

### ISSUE THREAD

**Issue by examknow** [examknow/MH-WikiBot#3]
The !log command is not producing any output.

**Comment by sario528** [comment]
In bot.py line 416 should "sender" be "senderhost"?

**Comment by sario528** [comment]
Line 339 for !delete is also "sender" instead of "senderhost".

**Comment by examknow** [comment]
@sario528 Yes and that has been fixed. I also need to add that the !delete command has stopped working. These issues will need to be fixed before deploying the beta version.

**Comment by examknow** [comment]
!log has been fixed

**Comment by examknow** [comment]
The !delete was an issue with the bot password which has since been resolved. I am now closing this issue as resolved.
